## This workflow will build and distribute the Android app using Fastlane and Firebase App Distribution
name: Android Fastlane with Firebase App Distribution Workflow

## this workflow will run on push to main branch
on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # … JDK & Flutter setup …

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.7"
          bundler-cache: true
          working-directory: android

      - name: Add Linux platform to Gemfile.lock
        working-directory: android
        run: bundle lock --add-platform x86_64-linux

      - name: Build and Distribute App
        working-directory: android
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: bundle exec fastlane android firebase_distribution

